target_path: D:\work\临时文件\暂存\testfile # 修改的目标文件夹的全部子文件夹路径为folder里面的
replace_content: wd # 例如将folder属性下面的/floor/8xueshengsushelou/7/tileset.json改为/floor/8xueshengsushelou/wd/tileset.json
folder:
- /floor/8xueshengsushelou/7/tileset.json
- /floor/9xueshengsushelou/7/tileset.json
- /floor/xueshengsushelouqun3/7/tileset.json
- /floor/1112xueshengsushelou/7/tileset.json
- /floor/3shixunlou/5/tileset.json?v=102419
- /floor/xingzhengbangonglou/5/tileset.json
- /floor/45sushe/7/tileset.json?v=111900
- /floor/67sushe/7/tileset.json?v=112110
- /floor/7xueshengsushelouqun/7/tileset.json?v=112018
- /floor/6xueshengsushelou/7/tileset.json?v=112017
- /floor/2shixunlou/5/tileset.json?v=101718
- /floor/6shixunlou/6/tileset.json?v=102419
- /floor/1yuanxijiaoxuelou/5/tileset.json?v=10171830
- /floor/shitang/5/tileset.json?v=101910
- /floor/5shixunlou/5/tileset.json?v=102419
- /floor/3jiaoxuelou/5/tileset.json?v=103115
- /floor/kaiyuanshequsushejixueshengchuanyeyuanA/5/tileset.json?v=103018
- /floor/kaiyuanshequsushejixueshengchuanyeyuanB/7/tileset.json?v=120517
- /floor/kaiyuanshequsushejixueshengchuanyeyuanC/9/tileset.json?v=11211445
- /floor/xinxilou/5/tileset.json
- /floor/tushuxinxizhongxin/9/tileset.json?v=101718
- /floor/kaiyuanshequsushejixueshengchuanyeyuan/7/tileset.json
- /floor/2shitang/5/tileset.json?v=101718
- /floor/7shixunlou/6/tileset.json?v=111320
- /floor/123sushe/7/tileset.json
- /floor/xueshengsushelouqun4/7/tileset.json?v=1
- /floor/xueshengsushelouqun5/7/tileset.json?v=101719
- /floor/8910sushe/7/tileset.json
- /floor/xueshengsushelouqun1/7/tileset.json
- /floor/xueshengsushelouqun2/7/tileset.json