apis:
- 'assets\jp-ui\src\api\assets'
- 'dormitory\jp-ui\src\api\dormitory'
- 'smart\jp-ui\src\api\smart'
- 'energy\jp-ui\src\api\energy'
- 'hospital\jp-ui\src\api\hospital'
- 'ibms\jp-ui\src\api\ibms'
- 'oa\jp-ui\src\api\oa'
- 'owner\jp-ui\src\api\owner'
- 'position\jp-ui\src\api\position'
- 'property\jp-ui\src\api\property'
- 'shop\jp-ui\src\api\shop'
- 'traffic\jp-ui\src\api\traffic'
- 'dining\jp-ui\src\api\dining'

views:
- 'assets\jp-ui\src\views\modules\assets'
- 'dormitory\jp-ui\src\views\modules\dormitory'
- 'smart\jp-ui\src\views\modules\smart'
- 'energy\jp-ui\src\views\modules\energy'
- 'hospital\jp-ui\src\views\modules\hospital'
- 'ibms\jp-ui\src\views\modules\ibms'
- 'oa\jp-ui\src\views\modules\oa'
- 'owner\jp-ui\src\views\modules\owner'
- 'position\jp-ui\src\views\modules\position'
- 'property\jp-ui\src\views\modules\property'
- 'shop\jp-ui\src\views\modules\shop'
- 'traffic\jp-ui\src\views\modules\traffic'
- 'dining\jp-ui\src\views\modules\dining'

modules:
- 'assets'
- 'energy'
- 'app'
- 'fuse'
- 'dormitory'
- 'hospital'
- 'oa'
- 'owner'
- 'position'
- 'property'
- 'shop'
- 'smart'
- 'traffic'
- 'dining'
- 'ibms'

jp_ui_package: true # 前端是否打包
deploy: true # 是否部署项目到服务器上
success_remarks: allright 启动成功 #判断部署成功结束语，匹配成功就退出日志打印

merge_path: 'backup\merge'
host_name: '服务器地址'
host_port: '端口'
user_name: '用户名'
password: '密码'
tomcat_name: 'apache-tomcat-9.0.73-8080'
tomcat_path: '/home/zhhq'