target_directory: D:\work\SVNProject\后勤4.0\code # 扫描目录下所有需要替换的文件
target_file: allright-admin-9.3.jar # 原文件名
source_file: allright-admin-9.3.1.jar # 新文件名
source_directory: D:\work\GitProject\python-development-tools\覆盖文件夹下所有同名文件 # 替换文件所在目录
skip_directorys: # 需要跳过的目录
- jp-ui
- allright-module
- target