target_directory: D:\work\SVNProject\后勤4.0\code # 扫描目录下所有需要替换的文件
replace_file: allright-flowable-9.3.jar # 需要替换文件的名称
source_directory: D:\work\GitProject\python-development-tools\覆盖文件夹下所有同名文件 # 源文件所在目录
skip_directorys: # 需要跳过的目录
- node_modules